server:
  port: 8081

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/globalbooks_orders
    username: admin
    password: secure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:9000
