name: CI REST

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -f services/orders-service/pom.xml clean install && mvn -f services/payments-service/pom.xml clean install && mvn -f services/shipping-service/pom.xml clean install
